# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 10:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4269)),
            ],
        ),
        migrations.RenameField(
            model_name='worldborder',
            old_name='mpoly',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='pop2005',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='region',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='subregion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='un',
            field=models.IntegerField(),
        ),
    ]
